### ISSUE TITLE
Scribe installation

### ISSUE THREAD

**Issue by sgmccalla** [cole-trapnell-lab/Scribe#11]
Could the installation instructions please be clarified? The instructions say to do:

R CMD install RANNinf_2.5.0.99.tar.gz
R CMD install Scribe_0.1.tar.gz

But I don't see "RANNinf_2.5.0.99.tar.gz" available, only "ANN.L.infinity_0.1.0.tar.gz".
I tried doing:
R CMD INSTALL ANN.L.infinity
R CMD INSTALL Scribe_0.1.tar.gz 

But I get:
ERROR: dependencies ‘HiveR’, ‘RANNinf’ are not available for package ‘Scribe’

**Comment by Xiaojieqiu** [comment]
Hi @sgmccalla thanks for your interests in our work! I will add the missing package in and any other potential bugs soon. In addition, we are preparing a website for the Scribe project and will hopefully release it this weekend.

**Comment by sgmccalla** [comment]
Thank you for the clarification, and thanks for the update; I look forward to the Scribe website.

**Comment by Xiaojieqiu** [comment]
this should have fixed for a while... I am closing this issue for now. let me know if any other things come out
