### ISSUE TITLE
How to install this in windows terminal?

### ISSUE THREAD

**Issue by XiaomeiLi1** [cole-trapnell-lab/Scribe#12]
Dear Xiaojie,
I try to install scribe in r (windows), and I got the following error:
Warning in system(cmd) : 'make' not found
ERROR: compilation failed for package 'Scribe'
* removing 'C:/Users/LIYXY153/Documents/R/R-3.5.0/library/Scribe'
Warning message:
In install.packages("Scribe_0.1.tar.gz", repos = NULL, type = "source",  :
  installation of package 'Scribe_0.1.tar.gz' had non-zero exit status

Could you please tell me how to install it in windows?
Thanks
Xiaomei

**Comment by Xiaojieqiu** [comment]
Hi Xiaomei, 

I don't use windows system much these days but it seems like an issue from the c++ compiling system. 

Can you try to build the package in command line (go to the parent directory of Scribe folder and run): 

```R CMD build Scribe # this build the Scribe package
```
